#!/bin/sh

# install non-essential formulae tools
brew install font-fira-code-nerd-font

# install essential formulae tools
brew install ansible
brew install ansible-lint
brew install asdf
brew install bazelisk
brew install cf-terraforming
brew install direnv
brew install gnupg
brew install helm
brew install mtr
brew install nmap
brew isntall starship
brew isntall stow
brew install yadm
# installed via `asdf``
# brew install opentofu
# brew install terraform

# install essential cask tools
brew install --cask 1password-cli
brew install --cask orbstack
brew install --cask raycast
brew install --cask slack
brew install --cask warp
brew install --cask zed
